using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Randomizer
{
	public class StaticData
	{
		public static List<string> Locations = new List<string>
		{
			"BrinstarMorph",
			"BrinstarBallCannon",
			"BrinstarLong",
			"BrinstarCeilingEtank",
			"BrinstarAboveSuper",
			"BrinstarSuper",
			"BrinstarTopMissile",
			"BrinstarShortcutMissile",
			"BrinstarVaria",
			"BrinstarWorm",
			"BrinstarVariaETank",
			"BrinstarFirstMissile",
			"BrinstarHiveMissile",
			"BrinstarUnderBridge",
			"BrinstarPostHiveMissile",
			"BrinstarPillarMissile",
			"BrinstarBehindBombs",
			"BrinstarBombs",
			"BrinstarPostHiveETank",

			"KraidGiantHoppers",
			"KraidSaveMissile",
			"KraidCrumbleMissile",
			"KraidBoringRoom",
			"KraidSpace",
			"KraidLavaMissile",
			"KraidSpeed",
			"KraidWormMissile",
			"KraidPillarMissile",
			"KraidLavaFall",
			"KraidWormETank",
			"KraidSpeedJump",
			"KraidBallCannon",

			"NorfairPowerBomb",
			"NorfairLavaMissile",
			"NorfairScrew",
			"NorfairScrewMissile",
			"NorfairGripMissile",
			"NorfairUnderElevator",
			"NorfairWave",
			"NorfairBombSuper",
			"NorfairBottomHeatedFirst",
			"NorfairBottomHeatedSecond",
			"NorfairHeatedSparkMissile",
			"NorfairSpaceBoostMissile",
			"NorfairSpaceBoostSuper",
			"NorfairIce",
			"NorfairIceHeated",
			"NorfairHiJump",
			"NorfairBigRoom",
			"NorfairTopMissile",
			"NorfairLarvaEtank",
			"NorfairBallCannon",
			"NorfairShaftBottom",

			"RidleySWPuzzleBottom",
			"RidleySWPuzzleTop",
			"RidleyWestPillar",
			"RidleyStatueETank",
			"RidleyGravity",
			"RidleyFakeFloor",
			"RidleyUpperBallCannon",
			"RidleyLowerBallCannon",
			"RidleyImagoSuper",
			"RidleyAboveSuper",
			"RidleySidehopperSuper",
			"RidleyLongHall",
			"RidleyPillarMissile",
			"RidleyBallMissile",
			"RidleyBallSuper",
			"RidleySidehopperMissile",
			"RidleyOwlETank",
			"RidleyJumpyJumpy",
			"RidleyBombPuzzle",
			"RidleySpeedJump",

			"TourianSpaceBoost",
			"TourianUnderBrain",

			"CrateriaPowerBomb",
			"CrateriaGrip",
			"CrateriaMoat",
			"CrateriaStatueWater",
			"CrateriaPlasma",
			"CrateriaBallSpark",
			"CrateriaSuper",

			"ChozodiaCrateriaPowerBomb",
			"ChozodiaBombMaze",
			"ChozodiaZoomerMaze",
			"ChozodiaFirstRuinSuper",
			"ChozodiaCharlieSparkMissile",
			"ChozodiaCharlieSuper",
			"ChozodiaOutOfTheWay",
			"ChozodiaGlassTubeETank",
			"ChozodiaLavaSuper",
			"ChozodiaOriginalPowerBomb",
			"ChozodiaSecondPowerBomb",
			"ChozodiaGlassTubePowerBomb",
			"ChozodiaCharlieSpark",
			"ChozodiaShortcutSuper",
			"ChozodiaWorkbotSuper",
			"ChozodiaHullSuper",
			"ChozodiaSpaceJumpETank",
			"ChozodiaHullPowerBomb",
		};

		public static Dictionary<string, string> Items = new Dictionary<string, string>
		{
			{"MorphBall", "Morph" },
			{"PowerGrip", "PowerGrip" },
			{"Hi-Jump", "Hi-Jump" },
			{"SpeedBooster", "SpeedBooster" },
			{"ScrewAttack", "ScrewAttack" },
			{"SpaceJump", "SpaceJump" },
			{"VariaSuit", "VariaSuit" },
			{"GravitySuit", "GravitySuit" },
			{"ChargeBeam", "ChargeBeam" },
			{"LongBeam", "LongBeam" },
			{"IceBeam", "IceBeam" },
			{"WaveBeam", "WaveBeam" },
			{"PlasmaBeam", "PlasmaBeam" },
			{"Bomb", "Bombs" },
			{"PowerBombTank", "PowerBombs" },
			{"MissileTank", "Missile" },
			{"SuperMissileTank", "SuperMissile" },
			{"EnergyTank", "E-Tank" },

		};
	}
}
