using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VerifierClient
{
	public class StaticData
	{
		public static List<string> Locations = new List<string>
		{
			"BrinstarMorph",
			"BrinstarBallCannon",
			"Long",
			"BrinstarCeilingEtank",
			"BrinstarAboveSuper",
			"BrinstarSuper",
			"Bdoublerippermissile",
			"Bshortcutmissile",
			"Bvaria",
			"Bbeamst",
			"Bvariae",
			"B1stmissile",
			"Bhivemissile",
			"Bmissileunderbridge",
			"Baltcavewormmissiles",
			"Bpillarmissile",
			"Bbehindbombs",
			"Bbombs",
			"B1stetank",

			"Kgiantsidehoppers",
			"Ksavemissile",
			"Kziplinecrumblemissile",
			"Kboring",
			"Kspacejump",
			"KAWSmissile",
			"Kspeed",
			"Kpostawmissile",
			"Kpreawpillarmissile",
			"Klavafall",
			"Kawe",
			"Kspeedjump",
			"Kballcannonmissile",

			"Nearlypbs",
			"Npbmissile",
			"Nscrew",
			"Nscrewmissiles",
			"Ntutorialmissiles",
			"Nminispaceboost",
			"Nwave",
			"Njohnsupers",
			"Nheatedroommissile1",
			"Nheatedroommissile2",
			"Njohnmissiles",
			"Nspaceboostmissiles",
			"Nspaceboostsupers",
			"Nice",
			"Nminiheatedmissiles",
			"Nhijump",
			"Nhighrisemissile",
			"Ntopmissiles",
			"Nlarvaee",
			"Nballcannonmissile",
			"Nshinebreakmissile",

			"Rlower1stpuzzlemissiles",
			"Rupper1stpuzzlemissiles",
			"Riceclipmissile",
			"Rridleye",
			"Rgravity",
			"Rfakefloore",
			"Rupperballcannonmissiles",
			"Rlowerballcannonmissiles",
			"Rimagosupers",
			"Rmissileabovesupers",
			"Rsupers",
			"Rlonghallmissiles",
			"Rpillarmissiles",
			"Rmissileundersecondsupers",
			"Rsecondsupers",
			"Rsidehoppermissiles",
			"Rowle",
			"Rjumpyjumpy",
			"R2ndpuzzleroommissiles",
			"Rspeedjumpmissiles",

			"Tspaceboost",
			"Tmbpbs",

			"Crpbs",
			"Crpg",
			"Crmoatmissiles",
			"Crunkmissiles",
			"Crplasma",
			"Crballsparkmissile",
			"Crsupers",

			"Ch-Crpbs",
			"Chbombmazesupers",
			"Chzoomermazesuper",
			"Choutofthewaysupers",
			"Chcharliesparkmissile",
			"Chcharliesupers",
			"Choutofthewaypbs",
			"Chglasstubee",
			"Chlavasupers",
			"Chvanillapbs",
			"Chsecondpbs",
			"Chglasstubemissiles",
			"Chcharliesparke",
			"Chpbshortcutsupers",
			"Chworkbotsupers",
			"Chbottomoftheshipsupers",
			"Chspacejumpetank",
			"Chbottomoftheshippbs",
		};

		public static Dictionary<string, string> Items = new Dictionary<string, string>
		{
			{"MorphBall", "Morph" },
			{"PowerGrip", "PowerGrip" },
			{"Hi-Jump", "Hi-Jump" },
			{"SpeedBooster", "SpeedBooster" },
			{"ScrewAttack", "ScrewAttack" },
			{"SpaceJump", "SpaceJump" },
			{"VariaSuit", "VariaSuit" },
			{"GravitySuit", "GravitySuit" },
			{"ChargeBeam", "ChargeBeam" },
			{"LongBeam", "LongBeam" },
			{"IceBeam", "IceBeam" },
			{"WaveBeam", "WaveBeam" },
			{"PlasmaBeam", "PlasmaBeam" },
			{"Bomb", "Bombs" },
			{"PowerBombTank", "PowerBombs" },
			{"MissileTank", "Missile" },
			{"SuperMissileTank", "SuperMissile" },
			{"EnergyTank", "E-Tank" },

		};
	}
}
